/// Baseline blocked terms: word|severity|contexts (contexts optional, comma-separated)
class BlockedWords {
  BlockedWords._();

  static const List<String> baselineLines = [
    'nigger|high',
    'nigga|high',
    'faggot|high',
    'kike|high',
    'spic|high',
    'chink|high',
    'retard|high',
    'pedophile|high',
    'child porn|high',
    'fuck|medium',
    'shit|medium',
    'bitch|medium',
    'asshole|medium',
    'bastard|medium',
    'cunt|medium',
    'dick|medium',
    'pussy|medium',
    'whore|medium',
    'slut|medium',
    'damn|low',
    'crap|low',
    'hell|low|post,message,bio',
    'piss|low',
    'madarchod|high',
    'behenchod|high',
    'chutiya|medium',
    'bhosdike|high',
    'randi|medium',
    'harami|medium',
    'gaandu|medium',
    'puta|medium',
    'pendejo|medium',
    'cabron|medium',
    'maricon|high',
    'mierda|low',
    'kuss|medium',
    'sharmouta|medium',
    'kill yourself|high',
    'kys|high',
    'gas the|high',
    'heil hitler|high',
    'white power|high',
    'admin|medium|username',
    'moderator|medium|username',
    'gotchaa|medium|username',
  ];
}
