// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKndoRyI3OLgSb3lF25k1aDmmJbrWebcE',
    appId: '1:389547380059:web:3edfc86da709b0b7ccde7e',
    messagingSenderId: '389547380059',
    projectId: 'studio-1284397718-50704',
    authDomain: 'studio-1284397718-50704.firebaseapp.com',
    storageBucket: 'studio-1284397718-50704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_83qQu58gqQCtCjpvAav5P9ZjKm0o1Iw',
    appId: '1:389547380059:ios:e32620e331033cacccde7e',
    messagingSenderId: '389547380059',
    projectId: 'studio-1284397718-50704',
    storageBucket: 'studio-1284397718-50704.firebasestorage.app',
    iosBundleId: 'com.gotchaa.gotchaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_83qQu58gqQCtCjpvAav5P9ZjKm0o1Iw',
    appId: '1:389547380059:ios:e32620e331033cacccde7e',
    messagingSenderId: '389547380059',
    projectId: 'studio-1284397718-50704',
    storageBucket: 'studio-1284397718-50704.firebasestorage.app',
    iosBundleId: 'com.gotchaa.gotchaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUrKWuvfMskagkHWObjHfm7CH9hlGktus',
    appId: '1:389547380059:web:ab3079f68a1db8a0ccde7e',
    messagingSenderId: '389547380059',
    projectId: 'studio-1284397718-50704',
    authDomain: 'studio-1284397718-50704.firebaseapp.com',
    storageBucket: 'studio-1284397718-50704.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9tipeuG5XcMHPoA8AwW5YRlfIRZy80c',
    appId: '1:389547380059:android:c771a4eace6c0e76ccde7e',
    messagingSenderId: '389547380059',
    projectId: 'studio-1284397718-50704',
    storageBucket: 'studio-1284397718-50704.firebasestorage.app',
  );

}
