import 'dart:io';

void main() {
  final file = File('lib/core/l10n/app_localizations_x.dart');
  final content = file.readAsStringSync();

  final List<String> languages = [
    'en',
    'hi',
    'es',
    'pt',
    'ar',
    'fr',
    'de',
    'ru',
    'ja',
    'ko',
    'zh',
    'tr',
    'it',
    'nl'
  ];
  final Map<String, Map<String, String>> allData = {};

  // Extract keys and values from each language block
  for (final lang in languages) {
    final langRegex = RegExp("'$lang':\\s*\\{(.*?)\\},", dotAll: true);
    final match = langRegex.firstMatch(content);
    if (match != null) {
      final langContent = match.group(1)!;
      // We need a very robust regex for existing broken values
      // This regex looks for 'key': 'value' even if value is multiline or has escaped quotes
      final keyRegex = RegExp(
          "'([a-zA-Z0-9_]+)':\\s*(?:r?'''(.*?)'''|'(.*?)'|\"(.*?)\")",
          dotAll: true);
      final Map<String, String> keys = {};
      for (final keyMatch in keyRegex.allMatches(langContent)) {
        final key = keyMatch.group(1)!;
        final String value =
            keyMatch.group(2) ?? keyMatch.group(3) ?? keyMatch.group(4) ?? '';

        // If the value was cut off or has the escaping error, we'll fix it later by merging with 'en'
        // But for now, we just take what we found.
        keys[key] = value;
      }
      allData[lang] = keys;
    }
  }

  final enData = allData['en'] ?? {};

  // Create the new file content
  final buffer = StringBuffer();
  buffer.writeln('// Generated by reconstruct_l10n.dart');
  buffer.writeln("import 'package:flutter/material.dart';");
  buffer.writeln("import 'package:flutter_riverpod/flutter_riverpod.dart';");
  buffer.writeln("import '../providers/language_provider.dart';");
  buffer.writeln('');
  buffer.writeln('class AppLocalizationsConfig {');
  buffer.writeln('  static const languages = [');
  buffer.writeln(
      "    {'code': 'en', 'name': 'English', 'nativeName': 'English'},");
  buffer
      .writeln("    {'code': 'hi', 'name': 'Hindi', 'nativeName': 'हिन्दी'},");
  buffer.writeln(
      "    {'code': 'es', 'name': 'Spanish', 'nativeName': 'Español'},");
  buffer.writeln(
      "    {'code': 'pt', 'name': 'Portuguese', 'nativeName': 'Português'},");
  buffer.writeln(
      "    {'code': 'ar', 'name': 'Arabic', 'nativeName': 'العربية'},");
  buffer.writeln(
      "    {'code': 'fr', 'name': 'French', 'nativeName': 'Français'},");
  buffer.writeln(
      "    {'code': 'de', 'name': 'German', 'nativeName': 'Deutsch'},");
  buffer.writeln(
      "    {'code': 'ru', 'name': 'Russian', 'nativeName': 'Русский'},");
  buffer
      .writeln("    {'code': 'ja', 'name': 'Japanese', 'nativeName': '日本語'},");
  buffer.writeln("    {'code': 'ko', 'name': 'Korean', 'nativeName': '한국어'},");
  buffer.writeln("    {'code': 'zh', 'name': 'Chinese', 'nativeName': '中文'},");
  buffer.writeln(
      "    {'code': 'tr', 'name': 'Turkish', 'nativeName': 'Türkçe'},");
  buffer.writeln(
      "    {'code': 'it', 'name': 'Italian', 'nativeName': 'Italiano'},");
  buffer.writeln(
      "    {'code': 'nl', 'name': 'Dutch', 'nativeName': 'Nederlands'},");
  buffer.writeln('  ];');
  buffer.writeln('');
  buffer.writeln('  static const Map<String, Map<String, String>> data = {');

  for (final lang in languages) {
    buffer.writeln("    '$lang': {");
    final langData = allData[lang] ?? {};

    // Use all keys from English to ensure full coverage
    for (final key in enData.keys) {
      String value = langData[key] ?? enData[key]!;

      // Validation: If value is too short or looks broken (ends in \), fallback to English
      if (value.endsWith(r'\') || value.length < 2 && enData[key]!.length > 5) {
        value = enData[key]!;
      }

      // Escape any $ and use triple quotes for absolute safety
      final safeValue = value.replaceAll(r'$', r'\$');
      buffer.writeln("      '$key': r'''$safeValue''',");
    }
    buffer.writeln('    },');
  }

  buffer.writeln('  };');
  buffer.writeln('}');
  buffer.writeln('');
  buffer.writeln('// The rest of the file (extension tr and context)...');

  // Append the tail of the file
  final tailStart = content.indexOf('class TrData');
  if (tailStart != -1) {
    buffer.write(content.substring(tailStart));
  } else {
    buffer.writeln('class TrData {');
    buffer.writeln(
        '  static String tr(String key, String locale, {List<String>? args, Map<String, String>? namedArgs}) {');
    buffer.writeln(
        '    String text = AppLocalizationsConfig.data[locale]?[key] ?? ');
    buffer.writeln(
        "                 AppLocalizationsConfig.data['en']?[key] ?? key;");
    buffer.writeln('    if (args != null) {');
    buffer.writeln('      for (final arg in args) {');
    buffer.writeln("        text = text.replaceFirst('{}', arg);");
    buffer.writeln('      }');
    buffer.writeln('    }');
    buffer.writeln('    if (namedArgs != null) {');
    buffer.writeln('      namedArgs.forEach((k, v) {');
    buffer.writeln(r"        text = text.replaceAll('{${k}}', v);");
    buffer.writeln('      });');
    buffer.writeln('    }');
    buffer.writeln('    return text;');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.writeln('');
    buffer.writeln('extension AppLocalizationsX on BuildContext {');
    buffer.writeln(
        '  String tr(String key, {List<String>? args, Map<String, String>? namedArgs}) {');
    buffer.writeln(
        '    final locale = Localizations.localeOf(this).languageCode;');
    buffer.writeln(
        '    return TrData.tr(key, locale, args: args, namedArgs: namedArgs);');
    buffer.writeln('  }');
    buffer.writeln('}');
  }

  file.writeAsStringSync(buffer.toString());
  print('Localization file reconstructed successfully!');
}
